/// Nepali constants
/// [native] means 'एक' and [english] means 'one'

class NepaliConstants {
  /// Nepali numbers constants for native style conversion
  static final List<String> singleUnitsNative = [
    'शून्य',
    'एक',
    'दुई',
    'तीन',
    'चार',
    'पाँच',
    'छ',
    'सात',
    'आठ',
    'नौ',
    'दस',
    'एघार',
    'बाह्र',
    'तेह्र',
    'चौध',
    'पन्ध्र',
    'सोह्र',
    'सत्र',
    'अठार',
    'उन्नाइस',
    'बीस',
    'एक्काइस',
    'बाइस',
    'तेइस',
    'चौबिस',
    'पच्चिस',
    'छब्बिस',
    'सत्ताइस',
    'अठ्ठाइस',
    'उनन्तिस',
    'तीस',
    'एकतिस',
    'बत्तिस',
    'तेत्तिस',
    'चौँतिस',
    'पैँतिस',
    'छत्तिस',
    'सैँतिस',
    'अठतिस',
    'उनन्चालिस',
    'चालिस',
    'एकचालिस',
    'बयालिस',
    'त्रिचालिस',
    'चवालिस',
    'पैँतालिस',
    'छयालिस',
    'सच्चालिस',
    'अठचालिस',
    'उनन्पचास',
    'पचास',
    'एकाउन्न',
    'बाउन्न',
    'त्रिपन्न',
    'चउन्न',
    'पचपन्न',
    'छपन्न',
    'सन्ताउन्न',
    'अन्ठाउन्न',
    'उनन्साठी',
    'साठी',
    'एकसट्ठी',
    'बैसट्ठी',
    'त्रिसट्ठी',
    'चौंसट्ठी',
    'पैंसट्ठी',
    'छैंसट्ठी',
    'सत्सट्ठी',
    'अठसट्ठी',
    'उनन्सत्तरी',
    'सत्तरी',
    'एकहत्तर',
    'बहत्तर',
    'त्रिहत्तर',
    'चौहत्तर',
    'पचहत्तर',
    'छयहत्तर',
    'सतहत्तर',
    'अठहत्तर',
    'उनासी',
    'असी',
    'एकासी',
    'बयासी',
    'त्रियासी',
    'चौरासी',
    'पचासी',
    'छयासी',
    'सतासी',
    'अठासी',
    'उनान्नब्बे',
    'नब्बे',
    'एकान्नब्बे',
    'बयान्नब्बे',
    'त्रियान्नब्बे',
    'चौरान्नब्बे',
    'पन्चान्नब्बे',
    'छयान्नब्बे',
    'सन्तान्नब्बे',
    'अन्ठान्नब्बे',
    'उनान्सय',
    'सय'
  ];

  /// Nepali numbers constants for native style conversion
  static final List<String> countsNative = [
    'सय',
    'हजार',
    'लाख',
    'करोड',
    'अर्ब',
    'खर्ब'
  ];

  /// Nepali numbers constants for english style conversion
  static final List<String> singleUnitsNativeEnglishStyle = [
    'zero',
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve',
    'thirteen',
    'fourteen',
    'fifteen',
    'sixteen',
    'seventeen',
    'eightteen',
    'nineteen',
  ];

  /// Nepali numbers constants for english style conversion
  static final List<String> tensEnglishStyle = [
    'zero',
    'ten',
    'twenty',
    'thirty',
    'fourty',
    'fifty',
    'sixty',
    'seventy',
    'eighty',
    'ninety',
  ];

  /// Nepali numbers constants for nepali style conversion
  static final List<String> countsNativeEnglishStyle = [
    'hundred',
    'thousand',
    'lakh',
    'crore',
    'arab',
    'kharab',
  ];
}
